version: "3"
services:
  backend:
    build:
      context: backend
    networks:
      - copeland
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      OPEN_WEATHER_MAP_KEY: cf002751564a4c78f5f7ed479f1b9ba3
  frontend:
    build:
      context: frontend
    networks:
      - copeland
    environment:
      PORT: 3000
      BACKEND_URL: http://localhost:3001
    depends_on:
      - backend
    ports:
      - "3000:3000"

networks:
  copeland:
    driver: bridge